### ISSUE TITLE
Single-end reads?

### ISSUE THREAD

**Issue by sdewell** [phe-bioinformatics/emm-typing-tool#1]
Thank you for making this tool. I am having some issues running it. 

I have installed the dependencies, and have the required tools in my path. I have named the genome 'reference.seq' and created the blast db. 'emm_tsdna.fas' is in the same directory (edit_allele_file.sh run successfully) . The directory is named 'reference'.

I have single-end reads, paired-end reads are not available at the moment. When running:
./emm_typing.py -m reference -1 sample.R1.fastq.gz -o sample_out

I get an error message:

error with main function

The 'sample_out' directory is not created. 

When placing my reads file into a 'samples' directory and running:
./emm_typing.py -m reference -i samples  -o sample_out

I get this error message:

There was an error in the function 'align_and_get_scores'
____________________________________________________________
Traceback (most recent call last):
  File "/home/scottd/emm-typing-tool/modules/utility_functions.py", line 54, in try_and_except
    return function(*parameters, **named_parameters)
  File "/home/scottd/emm-typing-tool/modules/EMM_determiner_functions.py", line 288, in align_and_get_scores
    if os.path.exists(pair[0]) and os.path.exists(pair[1]):
IndexError: list index out of range
____________________________________________________________

The 'sample_out' directory is created. 

It looks like paired-reads might be a requirement ... if so any chance to use single reads?

Thanks for any help!

**Comment by gkapatai** [comment]
You are right. The problem lies with the single-end reads. I'm afraid I wrote this specifically for Illumina paired-end reads. I have no plans at the moment to change this for different input formats. Is there a way you can simulate illumina paired-end reads from your data? I usually, assemble the genome and use pIRS to simulate paired-end fastq files...
Btw, thank you for trying the tool and I'm really happy to hear you have been able to set up all prerequisites.

**Comment by sdewell** [comment]
Thank you for the quick reply! I was intending to create synthetic pairs next, so I'll give that a go. Thanks again!

**Comment by sdewell** [comment]
As an FYI, i made a revcomp of the single-read fastq ... far from ideal but did the job, and the reported emm-type was found. Thanks again!
